### ISSUE TITLE
【优化】多模块集成测试框架的 application.propertites 覆盖问题

### ISSUE THREAD

**Issue by CodeNoobKing** [koupleless/runtime#9]
多模块集成测试框架，当直接调用 samples 库下的已有工程时，会存在单 maven 项目的多个 application.propertites 的覆盖问题。
目前可以暂时用 activeProfile 能力绕过，但是仍有优化空间，最好是用户完全 0 成本解决。

**Comment by lvjing2** [comment]
已完成 https://github.com/koupleless/runtime/pull/15/files
